---
# tasks file for Ubuntu2004-CIS

- import_tasks: prelim.yml

- name: Include section 1 
  import_tasks: section_1/main.yml
  when: ubuntu2004cis_section1

- name: Include section 2
  import_tasks: section_2/main.yml
  when: ubuntu2004cis_section2



