---

- name: Gather distribution info
  # we need:
  # - hardware for ansible_mounts
  # - platform for ansible_architecture (ansible internal)
  # - virtual for ansible_virtualization_type
  setup:
      gather_subset: distribution,hardware,platform,virtual,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.1 or greater
  when: not ansible_version.full is version_compare('2.1', '>=')
  tags:
      - always

- name: "PRELIM | Run apt update"
  apt:
      update_cache: yes
  when:
      - ubuntu2004cis_rule_1_3_1 or
        ubuntu2004cis_rule_1_9

- name: "PRELIM | Check for autofs service"
  shell: "systemctl show autofs | grep LoadState | cut -d = -f 2"
  register: ubuntu2004cis_autofs_service_status
  changed_when: false
  check_mode: false
  when:
      - ubuntu2004cis_rule_1_1_23
