---

- name: "AUTOMATED | 1.1.2 | PATCH | Ensure /tmp is configured"
  mount:
      path: /tmp
      src: tmpfs
      state: mounted
      fstype: tmpfs
      opts: "{{ ubtu20cis_tmp_fstab_options }}"

  when:
    - ubuntu2004cis_rule_1_1_2

- name: |
    "AUTOMATED | 1.1.3 | PATCH | Ensure nodev option set on /tmp partition"
    "AUTOMATED | 1.1.4 | PATCH | Ensure nosuid option set on /tmp partition"
    "AUTOMATED | 1.1.5 | PATCH | Ensure noexec option set on /tmp partition"
  mount:
      name: /tmp
      src: tmpfs
      state: remounted
      fstype: tmpfs
      opts: "{{ ubtu20cis_tmp_fstab_options }}"
  when: 
    - ubuntu2004cis_rule_1_1_3
    - ubuntu2004cis_rule_1_1_4
    - ubuntu2004cis_rule_1_1_5

- name: "AUTOMATED | 1.1.6 | PATCH | Ensure /dev/shm is configured"
  mount:
      name: /dev/shm
      src: tmpfs
      state: mounted
      fstype: tmpfs
      opts: "{{ ubtu20cis_dev_shm_fstab_options }}"
  when:
    - ubuntu2004cis_rule_1_1_6

- name: |
    "AUTOMATED | 1.1.7 | PATCH | Ensure nodev option set on /dev/shm partition"
    "AUTOMATED | 1.1.8 | PATCH | Ensure nosuid option set on /dev/shm partition"
    "AUTOMATED | 1.1.9 | PATCH | Ensure noexec option set on /dev/shm partition"
  mount:
      name: /dev/shm
      src: tmpfs
      state: remounted
      fstype: tmpfs
      opts: "{{ ubtu20cis_dev_shm_fstab_options }}"
  when:
    - ubuntu2004cis_rule_1_1_7
    - ubuntu2004cis_rule_1_1_8
    - ubuntu2004cis_rule_1_1_9


- name: AUTOMATED | 1.1.10 | PATCH | Ensure /var is mounted 
  block:
    - name: Create a new ext4 primary partition
      parted:
        device: /dev/xvdf
        number: 1
        state: present
        flags: [ lvm ]

    - shell: mv -f /var /var1

    - name: Create a directory
      file:
        path: /var
        state: directory
        mode: '0755'

    - name: format the xfs filesystem
      filesystem:
        fstype: xfs
        dev: /dev/xvdf1

    - mount:
        fstype: xfs
        src: /dev/xvdf1
        path: /var
        state: mounted

    - name: Copy file with owner and permissions
      shell: rsync -avzh /var1/ /var

    - name: Remove old var
      shell: rm -f /var1    
  when:
    - ubuntu2004cis_rule_1_1_10


