---
- name: "AUTOMATED | 5.4.1 | PATCH | Ensure password creation requirements are configured"
  block:
      - name: "AUTOMATED | 5.4.1 | PATCH | Ensure password creation requirements are configured | Install pam_pwquality module"
        apt:
            name: libpam-pwquality
            state: present

      - name: "AUTOMATED | 5.4.1 | PATCH | Ensure password creation requirements are configured | Add minlen"
        lineinfile:
            path: /etc/security/pwquality.conf
            regexp: '^minlen|^# minlen'
            line: minlen = 14

      - name: "AUTOMATED | 5.4.1 | PATCH | Ensure password creation requirements are configured | Add minclass"
        lineinfile:
            path: /etc/security/pwquality.conf
            regexp: '^minclass|^# minclass'
            line: 'minclass = 4'

      - name: "AUTOMATED | 5.4.1 | AUDIT | Ensure password creation requirements are configured | Confirm pwquality module in common-password"
        command: grep 'password.*requisite.*pam_pwquality.so' /etc/pam.d/common-password
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubuntu2004cis_5_4_1_pam_pwquality_state

      - name: "AUTOMATED | 5.4.1 | PATCH | Ensure password creation requirements are configured | Set retry to 3 if pwquality exists"
        pamd:
            name: common-password
            type: password
            control: requisite
            module_path: pam_pwquality.so
            module_arguments: 'retry=3'
            state: args_present
        when: ubuntu2004cis_5_4_1_pam_pwquality_state.stdout | length > 0

      - name: "AUTOMATED | 5.4.1 | PATCH | Ensure password creation requirements are configured | Set retry to 3 if pwquality does not exist"
        pamd:
            name: common-password
            type: password
            control: required
            module_path: pam_permit.so
            new_type: password
            new_control: requisite
            new_module_path: pam_pwquality.so
            module_arguments: 'retry=3'
            state: after
        when: ubuntu2004cis_5_4_1_pam_pwquality_state.stdout | length == 0
  when:
      - ubuntu2004cis_rule_5_4_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.4.1
      - pam

- name: "AUTOMATED | 5.4.2 | PATCH | Ensure lockout for failed password attempts is configured"
  command: /bin/true
  changed_when: false
  failed_when: false
  check_mode: false
  when:
      - ubuntu2004cis_rule_5_4_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.4.2
      - pamd
      - notimplemented

- name: "AUTOMATED | 5.4.3 | PATCH | Ensure password reuse is limited"
  block:
      - name: "AUTOMATED | 5.4.3 | AUDIT | Ensure password reuse is limited | Confirm pam_pwhistory.so in common-password"
        command: grep 'password.*required.*pam_pwhistory.so' /etc/pam.d/common-password
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubuntu2004cis_5_4_3_pam_pwhistory_state

      - name: "AUTOMATED | 5.4.3 | PATCH | Ensure password reuse is limited | Set remember value if pam_pwhistory exists"
        pamd:
            name: common-password
            type: password
            control: required
            module_path: pam_pwhistory.so
            module_arguments: 'remember={{ ubuntu2004cis_pamd_pwhistory_remember }}'
            state: args_present
        when: ubuntu2004cis_5_4_3_pam_pwhistory_state.stdout | length > 0

      - name: "AUTOMATED | 5.4.3 | PATCH | Ensure password reuse is limited | Set remember value if pam_pwhistory does no exist"
        lineinfile:
            path: /etc/pam.d/common-password
            line: 'password        required                        pam_pwhistory.so remember={{ ubuntu2004cis_pamd_pwhistory_remember }}'
            insertafter: '^# end of pam-auth-update config'
        when: ubuntu2004cis_5_4_3_pam_pwhistory_state.stdout | length == 0
  when:
      - ubuntu2004cis_rule_5_4_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.4.3
      - pamd

- name: "AUTOMATED | 5.4.4 | PATCH | Ensure password hashing algorithm is SHA-512"
  block:
      - name: "AUTOMATED | 5.4.4 | AUDIT | Ensure password hashing algorithm is SHA-512 | Confirm pam_unix.so"
        shell: grep -E '^\s*password\s+(\S+\s+)+pam_unix\.so\s+(\S+\s+)*sha512\s*(\S+\s*)*(\s+#.*)?$' /etc/pam.d/common-password
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubuntu2004cis_5_4_4_pam_unix_state

      - name: "AUTOMATED | 5.4.4 | PATCH | Ensure password hashing algorithm is SHA-512 | Set hashing if pam_unix.so exists"
        pamd:
            name: common-password
            type: password
            control: '[success=1 default=ignore]'
            module_path: pam_unix.so
            module_arguments: sha512
            state: args_present
        when: ubuntu2004cis_5_4_4_pam_unix_state.stdout | length > 0

      - name: "AUTOMATED | 5.4.4 | PATCH | Ensure password hashing algorithm is SHA-512 | Set hashing if pam_unix.so does not exist"
        lineinfile:
            path: /etc/pam.d/common-password
            line: 'password        [success=1 default=ignore]      pam_unix.so sha512'
            insertafter: '^# end of pam-auth-update config'
        when: ubuntu2004cis_5_4_4_pam_unix_state.stdout | length == 0
  when:
      - ubuntu2004cis_rule_5_4_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.4.4
      - pamd