---
- name: "AUTOMATED | 6.2.1 | AUDIT | Ensure accounts in /etc/passwd use shadowed passwords"
  block:
      - name: "AUTOMATED | 6.2.1 | AUDIT | Ensure accounts in /etc/passwd use shadowed passwords | Get users not using shadowed passwords"
        command: awk -F':' '($2 != "x" ) { print $1}' /etc/passwd
        changed_when: false
        failed_when: false
        register: ubuntu2004cis_6_2_1_nonshadowed_users

      - name: "AUTOMATED | 6.2.1 | AUDIT | Ensure accounts in /etc/passwd use shadowed passwords | Alert on findings"
        debug:
            msg:
                - "ALERT! You have users that are not using a shadowed password. Please convert the below accounts to use a shadowed password"
                - "{{ ubuntu2004cis_6_2_1_nonshadowed_users.stdout_lines }}"
        when:
            - ubuntu2004cis_6_2_1_nonshadowed_users.stdout | length > 0
  when:
      - ubuntu2004cis_rule_6_2_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_6.2.1
      - user_accounts

- name: "AUTOMATED | 6.2.2 | PATCH | Ensure password fields are not empty"
  block:
      - name: "AUTOMATED | 6.2.2 | AUDIT | Ensure password fields are not empty | Find users with no password"
        shell: awk -F":" '($2 == "" ) { print $1 }' /etc/shadow
        changed_when: no
        check_mode: false
        register: ubuntu2004cis_6_2_2_empty_password_acct

      - name: "AUTOMATED | 6.2.2 | PATCH | Ensure password fields are not empty | Lock users with empty password"
        user:
            name: "{{ item }}"
            password_lock: yes
        with_items:
            - "{{ ubuntu2004cis_6_2_2_empty_password_acct.stdout_lines }}"
        when: ubuntu2004cis_6_2_2_empty_password_acct.stdout | length > 0
  when:
      - ubuntu2004cis_rule_6_2_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.2.2
      - user
      - permissions

- name: "AUTOMATED | 6.2.3 | AUDIT | Ensure all groups in /etc/passwd exist in /etc/group"
  block:
      - name: "AUTOMATED | 6.2.3 | AUDIT | Ensure all groups in /etc/passwd exist in /etc/group | Check /etc/passwd entries"
        shell: pwck -r | grep 'no group' | awk '{ gsub("[:\47]",""); print $2}'
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubuntu2004cis_6_2_3_passwd_gid_check

      - name: "AUTOMATED | 6.2.3 | AUDIT | Ensure all groups in /etc/passwd exist in /etc/group | Print message that all groups match between passwd and group files"
        debug:
            msg: "Good News! There are no users that have non-existent GUIDs (Groups)"
        when: ubuntu2004cis_6_2_3_passwd_gid_check.stdout | length == 0

      - name: "AUTOMATED | 6.2.3 | AUDIT | Ensure all groups in /etc/passwd exist in /etc/group | Print warning about users with invalid GIDs missing GID entries in /etc/group"
        debug:
            msg: "WARNING!!!! The following users have non-existent GIDs (Groups): {{ ubuntu2004cis_6_2_3_passwd_gid_check.stdout_lines | join (', ') }}"
        when: ubuntu2004cis_6_2_3_passwd_gid_check.stdout | length > 0
  when:
      - ubuntu2004cis_rule_6_2_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_6.2.3
      - groups

- name: "AUTOMATED | 6.2.4 | PATCH | Ensure all users' home directories exist"
  block:
      - name: capture audit task for missing homedirs
        block: &u20s_homedir_audit
            - name: "AUTOMATED | 6.2.4 | PATCH | Ensure all users' home directories exist | Find users missing home directories"
              shell: pwck -r | grep -vF -e "'/nonexistent'" | grep -P {{ ld_regex | quote }}
              check_mode: false
              register: ubuntu2004cis_users_missing_home
              changed_when: ubuntu2004cis_6_2_4_audit | length > 0
              # failed_when: 0: success, 1: no grep match, 2: pwck found something
              failed_when: ubuntu2004cis_users_missing_home.rc not in [0,1,2]

      ### NOTE: due to https://github.com/ansible/ansible/issues/24862 This is a shell command, and is quite frankly less than ideal.
      - name: "AUTOMATED | 6.2.4 | PATCH | Ensure all users' home directories exist| Creates home directories"
        command: "mkhomedir_helper {{ item }}"
        # check_mode: "{{ ubuntu2004cis_disruptive_check_mode }}"
        with_items: "{{ ubuntu2004cis_6_2_4_audit | map(attribute='id') | list }}"
        when:
            - ubuntu2004cis_users_missing_home is changed
            - ubuntu2004cis_disruption_high

      ### NOTE: Now we need to address that SELINUX will not let mkhomedir_helper create home directories for UUID < 500, so the ftp user will still show up in a pwck. Not sure this is needed, I need to confirm if that user is removed in an earlier task.
      ### ^ Likely doesn't matter as 6.2.7 defines "local interactive users" as those w/ uid 1000-4999
      - name: replay audit task
        block: *u20s_homedir_audit

      # CAUTION: debug loops don't show changed since 2.4:
      # Fix: https://github.com/ansible/ansible/pull/59958
      - name: "AUTOMATED | 6.2.4 | PATCH | Ensure all users' home directories exist | Alert about correcting owner and group"
        debug: msg="You will need to mkdir -p {{ item }} and chown properly to the correct owner and group."
        with_items: "{{ ubuntu2004cis_6_2_4_audit | map(attribute='dir') | list }}"
        changed_when: ubuntu2004cis_audit_complex
        when:
            - ubuntu2004cis_users_missing_home is changed
  vars:
      ld_regex: >-
          ^user '(?P<user>.*)': directory '(?P<dir>.*)' does not exist$
      ld_users: "{{ ubuntu2004cis_users_missing_home.stdout_lines | map('regex_replace', ld_regex, '\\g<user>') | list }}"
      ubuntu2004cis_6_2_4_audit: "{{ ubuntu2004cis_passwd | selectattr('uid', '>=', 1000) | selectattr('id', 'in', ld_users) | list }}"
  when:
      - ubuntu2004cis_rule_6_2_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.2.4
      - user

- name: "AUTOMATED | 6.2.5 | PATCH | Ensure users own their home directories"
  file:
      path: "{{ item.dir }}"
      owner: "{{ item.id }}"
      state: directory
  with_items:
      - "{{ ubuntu2004cis_passwd }}"
  loop_control:
      label: "{{ ubuntu2004cis_passwd_label }}"
  when:
      - ubuntu2004cis_rule_6_2_5
      - item.uid >= 1000
      - item.dir != '/nonexistent'
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.2.5
      - user

- name: "AUTOMATED | 6.2.6 | PATCH | Ensure users' home directories permissions are 750 or more restrictive"
  command: /bin/true
  changed_when: false
  failed_when: false
  check_mode: false
  when:
      - ubuntu2004cis_rule_6_2_6
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.2.6
      - user

- name: "AUTOMATED | 6.2.7 | PATCH | Ensure users' dot files are not group or world writable"
  block:
      - name: "AUTOMATED | 6.2.7 | AUDIT | Ensure users' dot files are not group or world-writable | Check for files"
        shell: find /home/ -name "\.*" -perm /g+w,o+w
        changed_when: no
        failed_when: no
        check_mode: false
        register: ubuntu2004cis_6_2_7_audit

      - name: "AUTOMATED | 6.2.7 | AUDIT | Ensure users' dot files are not group or world-writable | Alert on files found"
        debug:
            msg: "Good news! We have not found any group or world-writable dot files on your sytem"
        failed_when: false
        changed_when: false
        when:
            - ubuntu2004cis_6_2_7_audit.stdout | length == 0

      - name: "AUTOMATED | 6.2.7 | PATCH | Ensure users' dot files are not group or world-writable | Changes files if configured"
        file:
            path: '{{ item }}'
            mode: go-w
        with_items: "{{ ubuntu2004cis_6_2_7_audit.stdout_lines }}"
        when:
            - ubuntu2004cis_6_2_7_audit.stdout | length > 0
            - ubuntu2004cis_dotperm_ansibleManaged
  when:
      - ubuntu2004cis_rule_6_2_7
      - ubuntu2004cis_disruption_high
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.2.7
      - user

- name: "AUTOMATED | 6.2.8 | PATCH | Ensure no users have .netrc files"
  file:
      dest: "~{{ item }}/.netrc"
      state: absent
  with_items:
      - "{{ ubuntu2004cis_users.stdout_lines }}"
  when:
      - ubuntu2004cis_rule_6_2_8
      - ubuntu2004cis_disruption_high
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.2.8
      - user

- name: "AUTOMATED | 6.2.9 | PATCH | Ensure no users have .forward files"
  file:
      dest: "~{{ item }}/.forward"
      state: absent
  with_items:
      - "{{ ubuntu2004cis_users.stdout_lines }}"
  when:
      - ubuntu2004cis_rule_6_2_9
      - ubuntu2004cis_disruption_high
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.2.9
      - user

- name: "AUTOMATED | 6.2.10 | PATCH | Ensure no users have .rhosts files"
  file:
      dest: "~{{ item }}/.rhosts"
      state: absent
  with_items:
      - "{{ ubuntu2004cis_users.stdout_lines }}"
  when:
      - ubuntu2004cis_rule_6_2_10
      - ubuntu2004cis_disruption_high
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.2.10
      - user

- name: "AUTOMATED | 6.2.11 | PATCH | Ensure root is the only UID 0 account"
  block:
      - name: "AUTOMATED | 6.2.11 | AUDIT | Ensure root is the only UID 0 account | Get non-root users with UID of 0"
        shell: awk -F":" '($3 == 0 && $1 != \"root\") {i++;print $1 }' /etc/passwd
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubuntu2004cis_6_2_11_uid_0_notroot

      - name: "AUTOMATED | 6.2.11 | PATCH | Ensure root is the only UID 0 account | Lock UID 0 users"
        user:
            name: "{{ item }}"
            password_lock: yes
        with_items:
            - "{{ ubuntu2004cis_6_2_11_uid_0_notroot.stdout_lines }}"
        when:
            - ubuntu2004cis_disruption_high
            - ubuntu2004cis_6_2_11_uid_0_notroot.stdout | length > 0

      - name: "AUTOMATED | 6.2.11 | AUDIT | Ensure root is the only UID 0 account | Alert about accounts disruption high"
        debug:
            msg:
                - "ALERT!!!! You have non-root users with a UID of 0 and ubtu18cis_disruption_high enabled"
                - "This means the following accounts were password locked and will need to have the UID's manually adjusted"
                - "{{ ubuntu2004cis_6_2_11_uid_0_notroot.stdout_lines }}"
        when:
            - ubuntu2004cis_disruption_high
            - ubuntu2004cis_6_2_11_uid_0_notroot.stdout | length > 0

      - name: "AUTOMATED | 6.2.11 | AUDIT | Ensure root is the only UID 0 account | Alert about accounts disruption low"
        debug:
            msg:
                - "ALERT!!!! You have non-root users with a UID of 0 and ubtu18cis_disruption_high disabled"
                - "This means no action was taken, you will need to have the UID's of the users below manually adjusted"
                - "{{ ubuntu2004cis_6_2_11_uid_0_notroot.stdout_lines }}"
        when:
            - not ubuntu2004cis_disruption_high
            - ubuntu2004cis_6_2_11_uid_0_notroot.stdout | length > 0
  when:
      - ubuntu2004cis_rule_6_2_11
  tags:
      - level1-server
      - level1-workstation
      - automated
      - scored
      - rule_6.2.11
      - user
      - root

- name: "AUTOMATED | 6.2.12 | PATCH | Ensure root PATH Integrity"
  command: /bin/true
  changed_when: false
  failed_when: false
  check_mode: false
  when:
      - ubuntu2004cis_rule_6_2_12
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.2.12
      - user
      - root
      - notimplemented

- name: "AUTOMATED | 6.2.13 | AUDIT | Ensure no duplicate UIDs exist"
  block:
      - name: "AUTOMATED | 6.2.13 | AUDIT | Ensure no duplicate UIDs exist | Check for duplicate UIDs"
        shell: "pwck -r | awk -F: '{if ($3 in uid) print $1 ; else uid[$3]}' /etc/passwd"
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubuntu2004cis_6_2_13_user_uid_check

      - name: "AUTOMATED | 6.2.13 | AUDIT | Ensure no duplicate UIDs exist | Print message that no duplicate UIDs exist"
        debug:
            msg: "Good News! There are no duplicate UID's in the system"
        when: ubuntu2004cis_6_2_13_user_uid_check.stdout | length == 0

      - name: "AUTOMATED | 6.2.13 | AUDIT | Ensure no duplicate UIDs exist | Print warning about users with duplicate UIDs"
        debug:
            msg: "Warning!!!! The following users have UIDs that are duplicates: {{ ubuntu2004cis_6_2_13_user_uid_check.stdout_lines }}"
        when: ubuntu2004cis_6_2_13_user_uid_check.stdout | length > 0
  when:
      - ubuntu2004cis_rule_6_2_13
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_6.2.13
      - user

- name: "AUTOMATED | 6.2.14 | AUDIT | Ensure no duplicate GIDs exist"
  block:
      - name: "AUTOMATED | 6.2.14 | AUDIT | Ensure no duplicate GIDs exist | Check for duplicate GIDs"
        shell: "pwck -r | awk -F: '{if ($3 in users) print $1 ; else users[$3]}' /etc/group"
        changed_when: no
        failed_when: no
        check_mode: false
        register: ubuntu2004cis_6_2_14_user_user_check

      - name: "AUTOMATED | 6.2.14 | AUDIT | Ensure no duplicate GIDs exist | Print message that no duplicate GID's exist"
        debug:
            msg: "Good News! There are no duplicate GIDs in the system"
        when: ubuntu2004cis_6_2_14_user_user_check.stdout | length == 0

      - name: "AUTOMATED | 6.2.14 | AUDIT | Ensure no duplicate GIDs exist | Print warning about users with duplicate GIDs"
        debug:
            msg: "Warning: The following groups have duplicate GIDs: {{ ubuntu2004cis_6_2_14_user_user_check.stdout_lines }}"
        when: ubuntu2004cis_6_2_14_user_user_check.stdout | length > 0
  when:
      - ubuntu2004cis_rule_6_2_14
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_6.2.14
      - groups

- name: "AUTOMATED | 6.2.15 | AUDIT | Ensure no duplicate user names exist"
  block:
      - name: "AUTOMATED | 6.2.15 | AUDIT | Ensure no duplicate user names exist | Check for duplicate User Names"
        shell: "pwck -r | awk -F: '{if ($1 in users) print $1 ; else users[$1]}' /etc/passwd"
        changed_when: no
        failed_when: no
        check_mode: false
        register: ubuntu2004cis_6_2_15_user_username_check

      - name: "AUTOMATED | 6.2.15 | AUDIT | Ensure no duplicate user names exist | Print message that no duplicate user names exist"
        debug:
            msg: "Good News! There are no duplicate user names in the system"
        when: ubuntu2004cis_6_2_15_user_username_check.stdout | length == 0

      - name: "AUTOMATED | 6.2.15 | AUDIT | Ensure no duplicate user names exist | Print warning about users with duplicate User Names"
        debug:
            msg: "Warning: The following user names are duplicates: {{ ubuntu2004cis_6_2_15_user_username_check.stdout_lines }}"
        when: ubuntu2004cis_6_2_15_user_username_check.stdout | length > 0
  when:
      - ubuntu2004cis_rule_6_2_15
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_6.2.15
      - user

- name: "AUTOMATED | 6.2.16 | AUDIT | Ensure no duplicate group names exist"
  block:
      - name: "AUTOMATED | 6.2.16 | AUDIT | Ensure no duplicate group names exist | Check for duplicate group names"
        shell: 'getent passwd | cut -d: -f1 | sort -n | uniq -d'
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubuntu2004cis_6_2_16_group_group_check

      - name: "AUTOMATED | 6.2.16 | AUDIT | Ensure no duplicate group names exist | Print message that no duplicate groups exist"
        debug:
            msg: "Good News! There are no duplicate group names in the system"
        when: ubuntu2004cis_6_2_16_group_group_check.stdout | length == 0

      - name: "AUTOMATED | 6.2.16 | AUDIT | Ensure no duplicate group names exist | Print warning about users with duplicate group names"
        debug:
            msg: "Warning: The following group names are duplicates: {{ ubuntu2004cis_6_2_16_group_group_check.stdout_lines }}"
        when: ubuntu2004cis_6_2_16_group_group_check.stdout | length > 0
  when:
      - ubuntu2004cis_rule_6_2_16
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_6.2.16
      - groups

- name: "AUTOMATED | 6.2.17 | AUDIT | Ensure shadow group is empty"
  block:
      - name: "AUTOMATED | 6.2.17 | AUDIT | Ensure shadow group is empty | Get Shadow GID"
        shell: grep ^shadow /etc/group | cut -f3 -d":"
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubuntu2004cis_6_2_17_shadow_gid

      - name: "AUTOMATED | 6.2.17 | AUDIT | Ensure shadow group is empty | List of users with Shadow GID"
        shell: awk -F":" '($4 == "{{ ubuntu2004cis_6_2_17_shadow_gid.stdout }}") { print }' /etc/passwd | cut -f1 -d":"
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubuntu2004cis_6_2_17_users_shadow_gid

      - name: "AUTOMATED | 6.2.17 | AUDIT | Ensure shadow group is empty | Message on no users"
        debug:
            msg: "Good News! There are no users with the Shadow GID on your system"
        when: ubuntu2004cis_6_2_17_users_shadow_gid.stdout | length == 0

      - name: "AUTOMATED | 6.2.17 | AUDIT | Ensure shadow group is empty | Message on users with Shadow GID"
        debug:
            msg:
                - "WARNING!!!! There are users that are in the Shadow group"
                - "To conform to CIS standards no users should be in this group"
                - "Please move the users below into another group"
                - "{{ ubuntu2004cis_6_2_17_users_shadow_gid.stdout_lines }}"
        when: ubuntu2004cis_6_2_17_users_shadow_gid.stdout | length > 0
  when:
      - ubuntu2004cis_rule_6_2_17
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_6.2.17
      - groups
      - user