---

- name: "AUTOMATED | 1.6.1.1 | PATCH | Ensure AppArmor is installed"
  apt:
      name: ['apparmor', 'apparmor-utils']
      state: present
  when:
      - ubuntu2004cis_rule_1_6_1_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.6.1.1
      - apparmor


- name: "1.6.1.2 | Ensure Ensure AppArmor is enabled in the bootloader configuration (Automated)"
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="(((?!apparmor).)*)"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 apparmor=1 security=apparmor"'
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - update grub configuration
    - reapply permissions to bootloader configuration
    # ^ to handle the fact that handlers run after tasks which change bootloader config permissions
  when:
    - ubuntu2004cis_rule_1_6_1_2
  tags:
    - section1
    - rule_1_6_1_2
    - level_1


- name: "AUTOMATED | 1.6.1.3 | PATCH | Ensure all AppArmor Profiles are in enforce or complain mode"
  command: aa-enforce /etc/apparmor.d/*
  failed_when: false
  when:
      - ubuntu2004cis_rule_1_6_1_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.6.1.3
      - apparmor


- name: "AUTOMATED | 1.6.1.4 | PATCH | Ensure all AppArmor Profiles are enforcing"
  command: aa-enforce /etc/apparmor.d/*
  failed_when: false
  when:
      - ubuntu2004cis_rule_1_6_1_4
  tags:
      - level2-server
      - level2-workstation
      - automated
      - scored
      - patch
      - rule_1.6.1.4
      - apparmor