---
- name: "1.3.1 | PATCH | Ensure AIDE is installed"
  block:
      - name: "1.3.1 | PATCH | Ensure AIDE is installed"
        apt:
            name: ['aide', 'aide-common']
            state: present
            update_cache: true

      - name: "1.3.1 | L1 | PATCH | Ensure AIDE is installed | Configure AIDE"
        shell: aideinit && mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db
        args:
            warn: false
            creates: /var/lib/aide/aide.db
        changed_when: false
        failed_when: false
        async: 45
        poll: 0
        when: not ansible_check_mode #magic variable so that it doesnt make any changes to remote system

  when:
      - ubuntu2004cis_config_aide
      - ubuntu2004cis_rule_1_3_1

- name: "SCORED | 1.3.2 | PATCH | Ensure filesystem integrity is regularly checked"
  cron:
      name: Run AIDE integrity check weekly
      cron_file: "{{ ubuntu2004cis_aide_cron['cron_file'] }}"
      user: "{{ ubuntu2004cis_aide_cron['cron_user'] }}"
      minute: "{{ ubuntu2004cis_aide_cron['aide_minute'] | default('0') }}"
      hour: "{{ ubuntu2004cis_aide_cron['aide_hour'] | default('5') }}"
      day: "{{ ubuntu2004cis_aide_cron['aide_day'] | default('*') }}"
      month: "{{ ubuntu2004cis_aide_cron['aide_month'] | default('*') }}"
      weekday: "{{ ubuntu2004cis_aide_cron['aide_weekday'] | default('0') }}"
      job: "{{ ubuntu2004cis_aide_cron['aide_job'] }}"
  when:
      - ubuntu2004cis_rule_1_3_2
      - ubuntu2004cis_config_aide