---
- name: "AUTOMATED | 4.4 | PATCH | Ensure logrotate assigns appropriate permissions"
  lineinfile:
      path: /etc/logrotate.conf
      regexp: '^create'
      line: ' create {{ ubuntu2004cis_logrotate_create_settings }}'
  when:
      - ubuntu2004cis_rule_4_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.4
      - logrotate